### ISSUE TITLE
non-existent directories

### ISSUE THREAD

**Issue by cwulfman** [pulibrary/webspace-to-figgy-transfer#2]
The following filepaths are reported not to exist, even though they appear in file listings (`ls`; running `ls -a` produces warnings)

1. {'collection code': 'AC435', 'component': 'AC435_c2', 'filepath': '/archives_bd/bcadmin/univarchives/AC435/AR.2016.022/AR_2016_022_bag/data/cdo/PHMC/Logistics', 'level of access': 'open'}
2. {'collection code': 'AC435', 'component': 'AC435_c8', 'filepath': '/archives_bd/bcadmin/univarchives/AC435/AR.2016.022/AR_2016_022_bag/data/cdo/PHMC/Alumni', 'level of access': 'open'}
3. {'collection code': 'AC435', 'component': 'AC435_c10', 'filepath': '/archives_bd/bcadmin/univarchives/AC435/AR.2016.022/AR_2016_022_bag/data/cdo/PHMC/Board Member Positions', 'level of access': 'open'}
4. {'collection code': 'AC435', 'component': 'AC435_c12', 'filepath': '/archives_bd/bcadmin/univarchives/AC435/AR.2016.022/AR_2016_022_bag/data/cdo/PHMC/Programming', 'level of access': 'open'}
5. {'collection code': 'AC436', 'component': 'AC436_c2', 'filepath': '/archives_bd/bcadmin/univarchives/AC436/AR.2016.031/AR_2016_031_bag/data/cdo/Meetings and minutes', 'level of access': 'open'}

**Comment by aberdini** [comment]
Hmm. Yeah they are definitely there, not sure what the issue is -- maybe they need a trailing slash, since they are directories?

**Comment by cwulfman** [comment]
The problem seems to be that these directories include single-quote characters

> pulsys@lib-proc7:/mnt/hydra_sources/archives_bd/bcadmin/univarchives/AC435/AR.2016.022/AR_2016_022_bag/data/cdo/PHMC$ ls -l
total 0
drwxr-xr-x 2 deploy root 0 Apr 25  2016 'Activities Fair'
drwxr-xr-x 2 deploy root 0 Apr 25  2016 'Alumni '
drwxr-xr-x 2 deploy root 0 Apr 25  2016 'Board Member Positions '
drwxr-xr-x 2 deploy root 0 Apr 25  2016 'Cultural Intersectionality Committee'
drwxr-xr-x 2 deploy root 0 Apr 25  2016 'Discussion Questions'
drwxr-xr-x 2 deploy root 0 Apr 25  2016 'Event Sign-in Sheets'
drwxr-xr-x 2 deploy root 0 Apr 25  2016  Flyers
drwxr-xr-x 2 deploy root 0 Apr 25  2016 'Focus Groups'
drwxr-xr-x 2 deploy root 0 Apr 25  2016 'Institutional Memory'
drwxr-xr-x 2 deploy root 0 Apr 25  2016 'Listserv Emails'
drwxr-xr-x 2 deploy root 0 Apr 25  2016 'Logistics '
drwxr-xr-x 2 deploy root 0 Apr 25  2016 'Meeting Notes'
drwxr-xr-x 2 deploy root 0 Apr 25  2016 'Outreach Committee'
drwxr-xr-x 2 deploy root 0 Apr 25  2016  Photos
drwxr-xr-x 2 deploy root 0 Apr 25  2016 'Programming '
drwxr-xr-x 2 deploy root 0 Apr 25  2016 'Social Committee'
drwxr-xr-x 2 deploy root 0 Apr 25  2016 'Steering Committee Meeting'
drwxr-xr-x 2 deploy root 0 Apr 25  2016  Surveys-Forms
drwxr-xr-x 2 deploy root 0 Apr 25  2016  Tech
drwxr-xr-x 2 deploy root 0 Apr 25  2016 'Uncategorized Files'

That is confusing a number of  operating-system-level tools. I'm not even sure how to rename these.

**Comment by cwulfman** [comment]
Googling around, I'm seeing some comments that suggest Unix's `ls` tool puts single quotes around names that contain special characters of some sort.

**Comment by aberdini** [comment]
That's really odd. There don't seem to be any special characters anywhere I look at the files -- they are from an older collection. If you rename them in a significant way I just need to know so I can reflect that in the accession record -- removing single quotes that the system added is fine, but if we need to insert underscores for example, just keep me posted so I can record the action.

**Comment by regineheberlein** [comment]
Not sure if this is helpful--the only characters not in Basic Latin in AC435.EAD.xml are four instances of curly quotes/apostrophes in the top-level scopecontent. (AC436 has none.)

**Comment by escowles** [comment]
@cwulfman I do think that those directories have spaces, and that `ls` is indeed adding the single quotes. Sorry I forgot to mention that — it definitely confused me and was one of the complicating factors that made my first attempt to list the contents of all the directories fail. So assuming we're just dealing with spaces, then properly quoting the paths should work fine, right?

**Comment by cwulfman** [comment]
Thanks, @regineheberlein, but this particular issue isn't with the strings in the xml document; it is a matter of directory names (perhaps derived from strings in the xml document).  @aberdini , I can't see files -- I can only see listings from `ls` (and from the OS X Finder when I mount the `archives_bd` volume from diglibdata1.

If either of you is using Windows, could you try renaming one of those directories?  Try renaming the folder that appears to be named Logistics.

**Comment by cwulfman** [comment]
@escowles , there are other directories whose names contain spaces that do not exhibit this problem.  So far I've found no way to properly quote the paths.

>➜  PHMC pwd
/Volumes/archives_bd/bcadmin/univarchives/AC435/AR.2016.022/AR_2016_022_bag/data/cdo/PHMC
➜  PHMC ls -l
ls: Alumni : No such file or directory
ls: Board Member Positions : No such file or directory
ls: Logistics : No such file or directory
ls: Programming : No such file or directory
total 544
drwxrwxr-x  1 cwulfman  staff  16384 Apr 25  2016 Activities Fair
drwxrwxr-x  1 cwulfman  staff  16384 Apr 25  2016 Cultural Intersectionality Committee
drwxrwxr-x  1 cwulfman  staff  16384 Apr 25  2016 Discussion Questions
drwxrwxr-x  1 cwulfman  staff  16384 Apr 25  2016 Event Sign-in Sheets
drwxrwxr-x  1 cwulfman  staff  16384 Apr 25  2016 Flyers
drwxrwxr-x  1 cwulfman  staff  16384 Apr 25  2016 Focus Groups
drwxrwxr-x  1 cwulfman  staff  16384 Apr 25  2016 Institutional Memory
drwxrwxr-x  1 cwulfman  staff  16384 Apr 25  2016 Listserv Emails
drwxrwxr-x  1 cwulfman  staff  16384 Apr 25  2016 Meeting Notes
drwxrwxr-x  1 cwulfman  staff  16384 Apr 25  2016 Outreach Committee
drwxrwxr-x  1 cwulfman  staff  16384 Apr 25  2016 Photos
drwxrwxr-x  1 cwulfman  staff  16384 Apr 25  2016 Social Committee
drwxrwxr-x  1 cwulfman  staff  16384 Apr 25  2016 Steering Committee Meeting
drwxrwxr-x  1 cwulfman  staff  16384 Apr 25  2016 Surveys-Forms
drwxrwxr-x  1 cwulfman  staff  16384 Apr 25  2016 Tech
drwxrwxr-x  1 cwulfman  staff  16384 Apr 25  2016 Uncategorized Files
➜  PHMC

**Comment by aberdini** [comment]
@cwulfman Renaming the files is not a workable solution, aside from perhaps inserting underscores for spaces. It is essential for authenticity of our collections that we avoid file renaming wherever possible. I tried to remove the trailing space in the Logistics file name but Windows thinks I haven't changed anything and rejects the suggestion.

**Comment by cwulfman** [comment]
Are you able to see the contents of these directories in Windows, @aberdini ?

**Comment by aberdini** [comment]
@cwulfman Yes. Do you need me to look for something?

**Comment by regineheberlein** [comment]
Thought as much, thanks @cwulfman—just checked the EADs thinking the directory names might have been pulled from the unittitles. Sorry to add noise.

**Comment by cwulfman** [comment]
Looks like there were control characters at the ends of those directory names. I logged onto the Isilon and changed the names to remove them.
